// Generated by Wrangler by running `wrangler types`

interface Env {
	OAUTH_CLIENT_ID: "356031833702-7ggmg5b7m57h9n0knaopql5mmand89gr.apps.googleusercontent.com";
	SITE_URL: "https://micboard.jacksonhorton.workers.dev" | "http://localhost:8787";
	ALLOW_HTTP_LOGINS: "false" | "true";
	DB: D1Database;
	ASSETS: Fetcher;
}
